### ISSUE TITLE
bug: Pane size changes when selecting order

### ISSUE THREAD

**Issue by palomato** [BibliothecaDAO/eternum#330]
<img width="1497" alt="order_window" src="https://github.com/BibliothecaDAO/eternum/assets/42439169/661d0899-a774-4f5d-a4c2-77c2b0967f76">

When starting a new game, the selecting an Order pane size changes depending on how much text is in that Order's description. For example, Power makes a short pane and enlightenment a tall pane. The change in pane size also changes the location of the buttons. This is on desktop.

Suggestion: Standardize pane height regardless of text description to keep buttons in the same location, left-align text.

**Comment by aymericdelab** [comment]
gm ser, thank you for opening the issue, i have fixed the size of the container so that the "Settle Realm" button stays in place

![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/0a77163c-539e-4f59-b17c-d3e75548383a)
![image](https://github.com/BibliothecaDAO/eternum/assets/38816784/1730325f-08d7-4896-9672-d209ad4c77ef)
