### ISSUE TITLE
Settle realms starting form the middle of the map

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#379]
**Feature**
In order to allow for easier interactions between players at the start of the game, they should all start from the center of the map, and go further as more realms are centred.

**Solution**
Find a way to define new locations for the realms so that the lower the realms id, the closer they are on the center.
If possible, make it so that realms are still grouped together by order.

**Comment by aymericdelab** [comment]
@ponderingdemocritus i was thinking that we could potentially do a pie type settlement like this, where each order would start from the center, but still be grouped by order:
<img width="767" alt="image" src="https://github.com/BibliothecaDAO/eternum/assets/38816784/fe5af01c-3893-4157-bef6-948176a58e49">

**Comment by credence0x** [comment]
> Find a way to define new locations for the realms so that the lower the realms id, the closer they are on the center.
If possible, make it so that realms are still grouped together by order.
@aymericdelab 
do you have a solution for this..i think i have an idea..maybe youve already thought about  it. it basically just involves extraction only the locations of all realms we have currently, then we sort all by distance from the center. then we assign realm locations in ascending order, as they are settled. 

it'll mean that realms won't necessarily be settled around circles though

**Comment by r0man1337** [comment]
I think that the more natural way is to freely choose hex for the settlement of the Realm, this adds more variability and game theory is included - you need to choose a point so that it is convenient to trade with neighbors and be more protected from attacks. 
Alternatively, you can choose hex away from everyone (let's say you have a set of Realms with all the necessary resources), and you can conquer more territory for your order away from everyone, but at the same time attract attention for future settlements. 

I don't think we should strictly define positions, instead of giving them to the players to choose from. The goal of the game is to control as many territories as possible, and tactics and strategy should be determined by the players, and not be laid out in the map. What is the point of war if we separate an equal piece for each order?

It is only necessary to determine the starting boundaries of the game zone, and come up with a law for its expansion. For example, building 50 new hyperstructures to expand the map by N hexes in all directions.

**Comment by aymericdelab** [comment]
Im all for allowing the player to settle their realm on the location they want. Don't think it's high priority though atm. Maybe let's go with credence suggestion for now. And create a new issue around choosing location.
