### ISSUE TITLE
setting exit button does not work

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaDAO/eternum#57]
![image](https://github.com/BibliothecaDAO/eternum/assets/53105057/7852f66f-1eb1-4762-8928-9016a5e2df22)

When I click this "X", nothing happens. The settings menu stays present.

**Comment by Fomentador** [comment]
@r0man1337 
While in the settings menu the _X_ button does nothing, in other menus it serves to clear the filters/options selected in the menu. This is extremely confusing since the _X_ icon is universally known as an icon to close windows. 

In these menus (the Market filter menus for Order and Resource) I suggest:
- [ ] Replacing the _X_ icon for a "Clear all" text, that only appears if and when an option is marked inside the menu. This removes all confusion and makes the purpose of the button clear for players.

**Comment by r0man1337** [comment]
Fixed in #91
