### ISSUE TITLE
[cairo] refactor transport system

### ISSUE THREAD

**Issue by aymericdelab** [BibliothecaDAO/eternum#586]
current transport system has some limitations:

- **improve donkey balance**: caravans are hard to manage, once you have created them, they need to be back at the realm who created them to be "redeemed" so that they can be reused. This is done by using a QuantityTracker model which tracks the number of donkeys instantiated by each realm. The available donkeys are then calculated based on the number of cities of the realm - the amount instantiated. This currently limits only realms to hold a donkey balance. A more elegant solution would be to define either a Donkey model which holds the balance available for any entity. We could even reuse the Resource model for donkeys. (maybe 3-4 hours)

- **generalise round trips:** currently round trips can only be used in the trading to go pick up resources. We should be able to call them outside of trading to either pickup resources or deposit resources.  (maybe 1 day)

- **usefulness of Caravan model**: the goal of the caravan model was to be able to bundle multiple entities together, even of different types like 1 army and 1 donkey, to transport things. Currently we always use containing only one entity of multiple donkeys, adding a layer of complexity that is not useful atm. 

@credence0x @ponderingdemocritus

**Comment by ponderingdemocritus** [comment]
I like the idea of turning Donkeys into resources.

They could be generated/purchased on a Realm and traded. It also means they would exist naturally at a bank and players could purchase them if they were in a pinch. And yes they would also exist on an Entity.

Perhaps instead of round trips we just define them as one-off burn resources. That would simplify everything.

So the loop would be:

Generate donkeys -> transport with them -> burns donkey resource

**Comment by credence0x** [comment]
fixed in #593
